package datas;

import java.sql.SQLException;

import models.Address;
import models.Furniture;
import models.Property;
import models.Role;
import models.Room;
import models.RoomType;
import models.User;

public class MainJdbc {
    jdbcDataAccess dataAccess;

    public MainJdbc() throws SQLException {
        dataAccess = new jdbcDataAccess();

        // Create a unused user to generate database using persistence
        @SuppressWarnings("unused")
        User userX = new User();

        // Wait 5 seconds for database to be created
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

        if(dataAccess.getUserById(1) != null){
            System.out.println("Datas already exist, no need to create them again");
            return;
        }

        // User definition
        User user1 = new User(1, "Jean-Luc", "Dubois", Role.AGENT);
        User user2 = new User(2, "Marie-Claire", "Lefevre", Role.OCCUPANT);
        User user3 = new User(3, "Antoine", "Dupont", Role.OWNER);
        User user4 = new User(4, "Camille", "Lambert", Role.OCCUPANT);
        User user5 = new User(5, "Sophie", "Martin", Role.OCCUPANT);
        User user6 = new User(6, "Pierre", "Leclerc", Role.OWNER);
        User user7 = new User(7, "Amélie", "Renault", Role.OWNER);
        dataAccess.addUser(user1);
        dataAccess.addUser(user2);
        dataAccess.addUser(user3);
        dataAccess.addUser(user4);
        dataAccess.addUser(user5);
        dataAccess.addUser(user6);
        dataAccess.addUser(user7);

        // Address definition
        Address address1 = new Address("Rue de la Paix", "75000", "1", "Paris");
        Address address2 = new Address("Rue de la Liberté", "69000", "2", "Lyon");
        Address address3 = new Address("Rue de la République", "13000", "3", "Marseille");
        Address address4 = new Address("Rue de la Gare", "31000", "4", "Toulouse");
        Address address5 = new Address("Rue de la Mairie", "44000", "5", "Nantes");
        Address address6 = new Address("Rue de l'Église", "35000", "6", "Rennes");
        Address address7 = new Address("Rue de la Poste", "59000", "7", "Lille");
        Address address8 = new Address("Rue de l'École", "67000", "8", "Strasbourg");
        Address address9 = new Address("Rue de la Gendarmerie", "68000", "9", "Mulhouse");
        Address address10 = new Address("Rue de la Préfecture", "25000", "10", "Besançon");
        dataAccess.addAddress(address1);
        dataAccess.addAddress(address2);
        dataAccess.addAddress(address3);
        dataAccess.addAddress(address4);
        dataAccess.addAddress(address5);
        dataAccess.addAddress(address6);
        dataAccess.addAddress(address7);
        dataAccess.addAddress(address8);
        dataAccess.addAddress(address9);
        dataAccess.addAddress(address10);

        // Property definition
        Property property1 = new Property(address1, user3);
        Property property2 = new Property(address2, user6);
        Property property3 = new Property(address3, user7);
        Property property4 = new Property(address4, user3);
        Property property5 = new Property(address5, user6);
        Property property6 = new Property(address6, user7);
        Property property7 = new Property(address7, user3);
        Property property8 = new Property(address8, user6);
        Property property9 = new Property(address9, user7);
        Property property10 = new Property(address10, user3);
        dataAccess.addProperty(property1);
        dataAccess.addProperty(property2);
        dataAccess.addProperty(property3);
        dataAccess.addProperty(property4);
        dataAccess.addProperty(property5);
        dataAccess.addProperty(property6);
        dataAccess.addProperty(property7);
        dataAccess.addProperty(property8);
        dataAccess.addProperty(property9);
        dataAccess.addProperty(property10);

        // Define at least a random number of rooms between 5 and 12 for each property
        Room room1 = new Room(property1, RoomType.BATHROOM, "Salle de bain 1");
        Room room2 = new Room(property1, RoomType.BATHROOM, "Salle de bain 2");
        Room room3 = new Room(property1, RoomType.BEDROOM, "Chambre 1");
        Room room4 = new Room(property1, RoomType.BEDROOM, "Chambre 2");
        Room room5 = new Room(property1, RoomType.KITCHEN, "Cuisine");
        Room room6 = new Room(property1, RoomType.LIVING_ROOM, "Salon");
        Room room7 = new Room(property1, RoomType.OFFICE, "Bureau");
        Room room8 = new Room(property1, RoomType.DINING_ROOM, "Salle à manger");
        Room room9 = new Room(property1, RoomType.BEDROOM, "Chambre 3");
        Room room10 = new Room(property1, RoomType.GARAGE, "Garage");
        Room room11 = new Room(property1, RoomType.BASEMENT, "Sous-sol");
        Room room12 = new Room(property2, RoomType.BATHROOM, "Salle de bain 1");
        Room room13 = new Room(property2, RoomType.BATHROOM, "Salle de bain 2");
        Room room14 = new Room(property2, RoomType.BEDROOM, "Chambre 1");
        Room room15 = new Room(property2, RoomType.BEDROOM, "Chambre 2");
        Room room16 = new Room(property2, RoomType.KITCHEN, "Cuisine");
        Room room17 = new Room(property2, RoomType.LIVING_ROOM, "Salon");
        Room room18 = new Room(property2, RoomType.OFFICE, "Bureau");
        Room room19 = new Room(property2, RoomType.DINING_ROOM, "Salle à manger");
        Room room20 = new Room(property3, RoomType.BEDROOM, "Chambre");
        Room room21 = new Room(property3, RoomType.BATHROOM, "Salle de bain");
        Room room22 = new Room(property3, RoomType.KITCHEN, "Cuisine");
        Room room23 = new Room(property3, RoomType.LIVING_ROOM, "Salon");
        Room room24 = new Room(property3, RoomType.OFFICE, "Bureau");
        Room room25 = new Room(property3, RoomType.DINING_ROOM, "Salle à manger");
        Room room26 = new Room(property4, RoomType.BEDROOM, "Chambre");
        Room room27 = new Room(property4, RoomType.BATHROOM, "Salle de bain");
        Room room28 = new Room(property4, RoomType.KITCHEN, "Cuisine");
        Room room29 = new Room(property4, RoomType.LIVING_ROOM, "Salon");
        Room room30 = new Room(property4, RoomType.OFFICE, "Bureau");
        Room room31 = new Room(property4, RoomType.DINING_ROOM, "Salle à manger");
        Room room32 = new Room(property5, RoomType.BEDROOM, "Chambre");
        Room room33 = new Room(property5, RoomType.BATHROOM, "Salle de bain");
        Room room34 = new Room(property5, RoomType.KITCHEN, "Cuisine");
        Room room35 = new Room(property5, RoomType.LIVING_ROOM, "Salon");
        Room room36 = new Room(property5, RoomType.OFFICE, "Bureau");
        Room room37 = new Room(property5, RoomType.DINING_ROOM, "Salle à manger");
        Room room38 = new Room(property6, RoomType.BEDROOM, "Chambre");
        Room room39 = new Room(property6, RoomType.BATHROOM, "Salle de bain");
        Room room40 = new Room(property6, RoomType.KITCHEN, "Cuisine");
        Room room41 = new Room(property6, RoomType.LIVING_ROOM, "Salon");
        Room room42 = new Room(property6, RoomType.OFFICE, "Bureau");
        Room room43 = new Room(property6, RoomType.DINING_ROOM, "Salle à manger");
        Room room44 = new Room(property7, RoomType.BEDROOM, "Chambre");
        Room room45 = new Room(property7, RoomType.BATHROOM, "Salle de bain");
        Room room46 = new Room(property7, RoomType.KITCHEN, "Cuisine");
        Room room47 = new Room(property7, RoomType.LIVING_ROOM, "Salon");
        Room room48 = new Room(property7, RoomType.OFFICE, "Bureau");
        Room room49 = new Room(property7, RoomType.DINING_ROOM, "Salle à manger");
        Room room50 = new Room(property8, RoomType.BEDROOM, "Chambre");
        Room room51 = new Room(property8, RoomType.BATHROOM, "Salle de bain");
        Room room52 = new Room(property8, RoomType.KITCHEN, "Cuisine");
        Room room53 = new Room(property8, RoomType.LIVING_ROOM, "Salon");
        Room room54 = new Room(property8, RoomType.OFFICE, "Bureau");
        Room room55 = new Room(property8, RoomType.DINING_ROOM, "Salle à manger");
        Room room56 = new Room(property9, RoomType.BEDROOM, "Chambre");
        Room room57 = new Room(property9, RoomType.BATHROOM, "Salle de bain");
        Room room58 = new Room(property9, RoomType.KITCHEN, "Cuisine");
        Room room59 = new Room(property9, RoomType.LIVING_ROOM, "Salon");
        Room room60 = new Room(property9, RoomType.OFFICE, "Bureau");
        Room room61 = new Room(property9, RoomType.DINING_ROOM, "Salle à manger");
        Room room62 = new Room(property10, RoomType.BEDROOM, "Chambre");
        Room room63 = new Room(property10, RoomType.BATHROOM, "Salle de bain");
        Room room64 = new Room(property10, RoomType.KITCHEN, "Cuisine");
        Room room65 = new Room(property10, RoomType.LIVING_ROOM, "Salon");
        Room room66 = new Room(property10, RoomType.OFFICE, "Bureau");
        Room room67 = new Room(property10, RoomType.DINING_ROOM, "Salle à manger");
        dataAccess.addRoom(room1);
        dataAccess.addRoom(room2);
        dataAccess.addRoom(room3);
        dataAccess.addRoom(room4);
        dataAccess.addRoom(room5);
        dataAccess.addRoom(room6);
        dataAccess.addRoom(room7);
        dataAccess.addRoom(room8);
        dataAccess.addRoom(room9);
        dataAccess.addRoom(room10);
        dataAccess.addRoom(room11);
        dataAccess.addRoom(room12);
        dataAccess.addRoom(room13);
        dataAccess.addRoom(room14);
        dataAccess.addRoom(room15);
        dataAccess.addRoom(room16);
        dataAccess.addRoom(room17);
        dataAccess.addRoom(room18);
        dataAccess.addRoom(room19);
        dataAccess.addRoom(room20);
        dataAccess.addRoom(room21);
        dataAccess.addRoom(room22);
        dataAccess.addRoom(room23);
        dataAccess.addRoom(room24);
        dataAccess.addRoom(room25);
        dataAccess.addRoom(room26);
        dataAccess.addRoom(room27);
        dataAccess.addRoom(room28);
        dataAccess.addRoom(room29);
        dataAccess.addRoom(room30);
        dataAccess.addRoom(room31);
        dataAccess.addRoom(room32);
        dataAccess.addRoom(room33);
        dataAccess.addRoom(room34);
        dataAccess.addRoom(room35);
        dataAccess.addRoom(room36);
        dataAccess.addRoom(room37);
        dataAccess.addRoom(room38);
        dataAccess.addRoom(room39);
        dataAccess.addRoom(room40);
        dataAccess.addRoom(room41);
        dataAccess.addRoom(room42);
        dataAccess.addRoom(room43);
        dataAccess.addRoom(room44);
        dataAccess.addRoom(room45);
        dataAccess.addRoom(room46);
        dataAccess.addRoom(room47);
        dataAccess.addRoom(room48);
        dataAccess.addRoom(room49);
        dataAccess.addRoom(room50);
        dataAccess.addRoom(room51);
        dataAccess.addRoom(room52);
        dataAccess.addRoom(room53);
        dataAccess.addRoom(room54);
        dataAccess.addRoom(room55);
        dataAccess.addRoom(room56);
        dataAccess.addRoom(room57);
        dataAccess.addRoom(room58);
        dataAccess.addRoom(room59);
        dataAccess.addRoom(room60);
        dataAccess.addRoom(room61);
        dataAccess.addRoom(room62);
        dataAccess.addRoom(room63);
        dataAccess.addRoom(room64);
        dataAccess.addRoom(room65);
        dataAccess.addRoom(room66);
        dataAccess.addRoom(room67);
        
        // For each room add some furnitures that matches room type ex: bed in bedroom
        Furniture furniture1 = new Furniture("Lavabo", room1, "Mur gauche");
        Furniture furniture2 = new Furniture("Douche", room1, "Mur droit");
        Furniture furniture3 = new Furniture("Baignoire", room2, "Mur gauche");
        Furniture furniture4 = new Furniture("Toilettes", room2, "Mur droit");
        Furniture furniture5 = new Furniture("Dérouleurs", room2, "Mur gauche");
        Furniture furniture6 = new Furniture("Lit", room3, "Mur gauche");
        Furniture furniture7 = new Furniture("Armoire", room3, "Mur droit");
        Furniture furniture8 = new Furniture("Lit", room4, "Mur gauche");
        Furniture furniture9 = new Furniture("Armoire", room4, "Mur droit");
        Furniture furniture10 = new Furniture("Table", room5, "Mur gauche");
        Furniture furniture11 = new Furniture("Chaises", room5, "Mur droit");
        Furniture furniture12 = new Furniture("Canapé", room6, "Mur gauche");
        Furniture furniture13 = new Furniture("Table basse", room6, "Mur droit");
        Furniture furniture14 = new Furniture("Bureau", room7, "Mur gauche");
        Furniture furniture15 = new Furniture("Chaise", room7, "Mur droit");
        Furniture furniture16 = new Furniture("Table", room8, "Mur gauche");
        Furniture furniture17 = new Furniture("Chaises", room8, "Mur droit");
        Furniture furniture18 = new Furniture("Lit", room9, "Mur gauche");
        Furniture furniture19 = new Furniture("Armoire", room9, "Mur droit");
        Furniture furniture20 = new Furniture("Voiture", room10, "Mur gauche");
        Furniture furniture21 = new Furniture("Outils", room10, "Mur droit");
        Furniture furniture22 = new Furniture("Lit", room11, "Mur gauche");
        Furniture furniture23 = new Furniture("Armoire", room11, "Mur droit");
        Furniture furniture24 = new Furniture("Lavabo", room12, "Mur gauche");
        Furniture furniture25 = new Furniture("Douche", room12, "Mur droit");
        Furniture furniture26 = new Furniture("Baignoire", room13, "Mur gauche");
        Furniture furniture27 = new Furniture("Toilettes", room13, "Mur droit");
        Furniture furniture28 = new Furniture("Dérouleurs", room13, "Mur gauche");
        Furniture furniture29 = new Furniture("Lit", room14, "Mur gauche");
        Furniture furniture30 = new Furniture("Armoire", room14, "Mur droit");
        Furniture furniture31 = new Furniture("Table basse", room14, "Mur droit");
        Furniture furniture32 = new Furniture("Lit", room15, "Mur gauche");
        Furniture furniture33 = new Furniture("Armoire", room15, "Mur droit");
        Furniture furniture34 = new Furniture("Table", room16, "Mur gauche");
        Furniture furniture35 = new Furniture("Chaises", room16, "Mur droit");
        Furniture furniture36 = new Furniture("Canapé", room17, "Mur gauche");
        Furniture furniture37 = new Furniture("Table basse", room17, "Mur droit");
        Furniture furniture38 = new Furniture("Bureau", room18, "Mur gauche");
        Furniture furniture39 = new Furniture("Chaise", room18, "Mur droit");
        Furniture furniture40 = new Furniture("Table", room19, "Mur gauche");
        Furniture furniture41 = new Furniture("Chaises", room19, "Mur droit");
        Furniture furniture42 = new Furniture("Lit", room20, "Mur gauche");
        Furniture furniture43 = new Furniture("Armoire", room20, "Mur droit");
        Furniture furniture44 = new Furniture("Voiture", room21, "Mur gauche");
        Furniture furniture45 = new Furniture("Outils", room21, "Mur droit");
        Furniture furniture46 = new Furniture("Lit", room22, "Mur gauche");
        Furniture furniture47 = new Furniture("Armoire", room22, "Mur droit");
        Furniture furniture48 = new Furniture("Lavabo", room23, "Mur gauche");
        Furniture furniture49 = new Furniture("Douche", room23, "Mur droit");
        Furniture furniture50 = new Furniture("Baignoire", room24, "Mur gauche");
        Furniture furniture51 = new Furniture("Toilettes", room24, "Mur droit");
        Furniture furniture52 = new Furniture("Dérouleurs", room24, "Mur gauche");
        Furniture furniture53 = new Furniture("Lit", room25, "Mur gauche");
        Furniture furniture54 = new Furniture("Armoire", room25, "Mur droit");
        Furniture furniture55 = new Furniture("Table basse", room25, "Mur droit");
        Furniture furniture56 = new Furniture("Lit", room26, "Mur gauche");
        Furniture furniture57 = new Furniture("Armoire", room26, "Mur droit");
        Furniture furniture58 = new Furniture("Table", room27, "Mur gauche");
        Furniture furniture59 = new Furniture("Chaises", room27, "Mur droit");
        Furniture furniture60 = new Furniture("Canapé", room28, "Mur gauche");
        Furniture furniture61 = new Furniture("Table basse", room28, "Mur droit");
        Furniture furniture62 = new Furniture("Bureau", room29, "Mur gauche");
        Furniture furniture63 = new Furniture("Chaise", room29, "Mur droit");
        Furniture furniture64 = new Furniture("Table", room30, "Mur gauche");
        Furniture furniture65 = new Furniture("Chaises", room30, "Mur droit");
        Furniture furniture66 = new Furniture("Lit", room31, "Mur gauche");
        Furniture furniture67 = new Furniture("Armoire", room31, "Mur droit");
        Furniture furniture68 = new Furniture("Voiture", room32, "Mur gauche");
        Furniture furniture69 = new Furniture("Outils", room32, "Mur droit");
        Furniture furniture70 = new Furniture("Lit", room33, "Mur gauche");
        Furniture furniture71 = new Furniture("Armoire", room33, "Mur droit");
        Furniture furniture72 = new Furniture("Lavabo", room34, "Mur gauche");
        Furniture furniture73 = new Furniture("Douche", room34, "Mur droit");
        Furniture furniture74 = new Furniture("Baignoire", room35, "Mur gauche");
        Furniture furniture75 = new Furniture("Toilettes", room35, "Mur droit");
        Furniture furniture76 = new Furniture("Dérouleurs", room35, "Mur gauche");
        Furniture furniture77 = new Furniture("Lit", room36, "Mur gauche");
        Furniture furniture78 = new Furniture("Armoire", room36, "Mur droit");
        Furniture furniture79 = new Furniture("Table basse", room36, "Mur droit");
        Furniture furniture80 = new Furniture("Lit", room37, "Mur gauche");
        Furniture furniture81 = new Furniture("Armoire", room37, "Mur droit");
        Furniture furniture82 = new Furniture("Table", room38, "Mur gauche");
        Furniture furniture83 = new Furniture("Chaises", room38, "Mur droit");
        Furniture furniture84 = new Furniture("Canapé", room39, "Mur gauche");
        Furniture furniture85 = new Furniture("Table basse", room39, "Mur droit");
        Furniture furniture86 = new Furniture("Bureau", room40, "Mur gauche");
        Furniture furniture87 = new Furniture("Chaise", room40, "Mur droit");
        Furniture furniture88 = new Furniture("Table", room41, "Mur gauche");
        Furniture furniture89 = new Furniture("Chaises", room41, "Mur droit");
        Furniture furniture90 = new Furniture("Lit", room42, "Mur gauche");
        Furniture furniture91 = new Furniture("Armoire", room42, "Mur droit");
        Furniture furniture92 = new Furniture("Voiture", room43, "Mur gauche");
        Furniture furniture93 = new Furniture("Outils", room43, "Mur droit");
        Furniture furniture94 = new Furniture("Lit", room44, "Mur gauche");
        Furniture furniture95 = new Furniture("Armoire", room44, "Mur droit");
        Furniture furniture96 = new Furniture("Lavabo", room45, "Mur gauche");
        Furniture furniture97 = new Furniture("Douche", room45, "Mur droit");
        Furniture furniture98 = new Furniture("Baignoire", room46, "Mur gauche");
        Furniture furniture99 = new Furniture("Toilettes", room46, "Mur droit");
        Furniture furniture100 = new Furniture("Dérouleurs", room46, "Mur gauche");
        Furniture furniture101 = new Furniture("Lit", room47, "Mur gauche");
        Furniture furniture102 = new Furniture("Armoire", room47, "Mur droit");
        Furniture furniture103 = new Furniture("Table basse", room47, "Mur droit");
        Furniture furniture104 = new Furniture("Lit", room48, "Mur gauche");
        Furniture furniture105 = new Furniture("Armoire", room48, "Mur droit");
        Furniture furniture106 = new Furniture("Table", room49, "Mur gauche");
        Furniture furniture107 = new Furniture("Chaises", room49, "Mur droit");
        Furniture furniture108 = new Furniture("Canapé", room50, "Mur gauche");
        Furniture furniture109 = new Furniture("Table basse", room50, "Mur droit");
        Furniture furniture110 = new Furniture("Bureau", room51, "Mur gauche");
        Furniture furniture111 = new Furniture("Chaise", room51, "Mur droit");
        Furniture furniture112 = new Furniture("Table", room52, "Mur gauche");
        Furniture furniture113 = new Furniture("Chaises", room52, "Mur droit");
        Furniture furniture114 = new Furniture("Lit", room53, "Mur gauche");
        Furniture furniture115 = new Furniture("Armoire", room53, "Mur droit");
        Furniture furniture116 = new Furniture("Scie à métaux", room54, "Mur gauche");
        Furniture furniture117 = new Furniture("Outils", room54, "Mur droit");
        Furniture furniture118 = new Furniture("Lit", room55, "Mur gauche");
        Furniture furniture119 = new Furniture("Armoire", room55, "Mur droit");
        Furniture furniture120 = new Furniture("Lavabo", room56, "Mur gauche");
        Furniture furniture121 = new Furniture("Douche", room56, "Mur droit");
        Furniture furniture122 = new Furniture("Baignoire", room57, "Mur gauche");
        Furniture furniture123 = new Furniture("Toilettes", room57, "Mur droit");
        Furniture furniture124 = new Furniture("Dérouleur", room57, "Mur gauche");
        Furniture furniture125 = new Furniture("Lit", room58, "Mur gauche");
        Furniture furniture126 = new Furniture("Armoire", room58, "Mur droit");
        Furniture furniture127 = new Furniture("Table basse", room58, "Mur droit");
        Furniture furniture128 = new Furniture("Lit", room59, "Mur gauche");
        Furniture furniture129 = new Furniture("Armoire", room59, "Mur droit");
        Furniture furniture130 = new Furniture("Table", room60, "Mur gauche");
        Furniture furniture131 = new Furniture("Chaises", room60, "Mur droit");
        Furniture furniture132 = new Furniture("Canapé", room61, "Mur gauche");
        Furniture furniture133 = new Furniture("Table basse", room61, "Mur droit");
        Furniture furniture134 = new Furniture("Bureau", room62, "Mur gauche");
        Furniture furniture135 = new Furniture("Chaise", room62, "Mur droit");
        Furniture furniture136 = new Furniture("Table", room63, "Mur gauche");
        Furniture furniture137 = new Furniture("Chaises", room63, "Mur droit");
        Furniture furniture138 = new Furniture("Lit", room64, "Mur gauche");
        Furniture furniture139 = new Furniture("Armoire", room64, "Mur droit");
        Furniture furniture140 = new Furniture("Tondeuse", room65, "Mur gauche");
        Furniture furniture141 = new Furniture("Outils", room65, "Mur droit");
        Furniture furniture142 = new Furniture("Lit", room66, "Mur gauche");
        Furniture furniture143 = new Furniture("Armoire", room66, "Mur droit");
        Furniture furniture144 = new Furniture("Lavabo", room67, "Mur gauche");
        Furniture furniture145 = new Furniture("Douche", room67, "Mur droit");
        Furniture furniture146 = new Furniture("Baignoire", room67, "Mur gauche");
        Furniture furniture147 = new Furniture("Toilettes", room67, "Mur droit");
        Furniture furniture148 = new Furniture("Dérouleur", room67, "Mur gauche");
        Furniture furniture149 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture150 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture151 = new Furniture("Table basse", room67, "Mur droit");
        Furniture furniture152 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture153 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture154 = new Furniture("Table", room67, "Mur gauche");
        Furniture furniture155 = new Furniture("Chaises", room67, "Mur droit");
        Furniture furniture156 = new Furniture("Canapé", room67, "Mur gauche");
        Furniture furniture157 = new Furniture("Table basse", room67, "Mur droit");
        Furniture furniture158 = new Furniture("Bureau", room67, "Mur gauche");
        Furniture furniture159 = new Furniture("Chaise", room67, "Mur droit");
        Furniture furniture160 = new Furniture("Table", room67, "Mur gauche");
        Furniture furniture161 = new Furniture("Chaises", room67, "Mur droit");
        Furniture furniture162 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture163 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture164 = new Furniture("Voiture", room67, "Mur gauche");
        Furniture furniture165 = new Furniture("Outils", room67, "Mur droit");
        Furniture furniture166 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture167 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture168 = new Furniture("Lavabo", room67, "Mur gauche");
        Furniture furniture169 = new Furniture("Douche", room67, "Mur droit");
        Furniture furniture170 = new Furniture("Baignoire", room67, "Mur gauche");
        Furniture furniture171 = new Furniture("Toilettes", room67, "Mur droit");
        Furniture furniture172 = new Furniture("Dérouleur", room67, "Mur gauche");
        Furniture furniture173 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture174 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture175 = new Furniture("Table basse", room67, "Mur droit");
        Furniture furniture176 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture177 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture178 = new Furniture("Table", room67, "Mur gauche");
        Furniture furniture179 = new Furniture("Chaises", room67, "Mur droit");
        Furniture furniture180 = new Furniture("Canapé", room67, "Mur gauche");
        Furniture furniture181 = new Furniture("Table basse", room67, "Mur droit");
        Furniture furniture182 = new Furniture("Bureau", room67, "Mur gauche");
        Furniture furniture183 = new Furniture("Chaise", room67, "Mur droit");
        Furniture furniture184 = new Furniture("Table", room67, "Mur gauche");
        Furniture furniture185 = new Furniture("Chaises", room67, "Mur droit");
        Furniture furniture186 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture187 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture188 = new Furniture("Voiture", room67, "Mur gauche");
        Furniture furniture189 = new Furniture("Outils", room67, "Mur droit");
        Furniture furniture190 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture191 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture192 = new Furniture("Lavabo", room67, "Mur gauche");
        Furniture furniture193 = new Furniture("Douche", room67, "Mur droit");
        Furniture furniture194 = new Furniture("Baignoire", room67, "Mur gauche");
        Furniture furniture195 = new Furniture("Toilettes", room67, "Mur droit");
        Furniture furniture196 = new Furniture("Dérouleur", room67, "Mur gauche");
        Furniture furniture197 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture198 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture199 = new Furniture("Table basse", room67, "Mur droit");
        Furniture furniture200 = new Furniture("Lit", room67, "Mur gauche");
        Furniture furniture201 = new Furniture("Armoire", room67, "Mur droit");
        Furniture furniture202 = new Furniture("Placard", room67, "Mur gauche");
        Furniture furniture203 = new Furniture("Meuble télévision", room67, "Mur gauche");
        Furniture furniture204 = new Furniture("Mini-frigo", room67, "Mur gauche");
        dataAccess.addFurniture(furniture1);
        dataAccess.addFurniture(furniture2);
        dataAccess.addFurniture(furniture3);
        dataAccess.addFurniture(furniture4);
        dataAccess.addFurniture(furniture5);
        dataAccess.addFurniture(furniture6);
        dataAccess.addFurniture(furniture7);
        dataAccess.addFurniture(furniture8);
        dataAccess.addFurniture(furniture9);
        dataAccess.addFurniture(furniture10);
        dataAccess.addFurniture(furniture11);
        dataAccess.addFurniture(furniture12);
        dataAccess.addFurniture(furniture13);
        dataAccess.addFurniture(furniture14);
        dataAccess.addFurniture(furniture15);
        dataAccess.addFurniture(furniture16);
        dataAccess.addFurniture(furniture17);
        dataAccess.addFurniture(furniture18);
        dataAccess.addFurniture(furniture19);
        dataAccess.addFurniture(furniture20);
        dataAccess.addFurniture(furniture21);
        dataAccess.addFurniture(furniture22);
        dataAccess.addFurniture(furniture23);
        dataAccess.addFurniture(furniture24);
        dataAccess.addFurniture(furniture25);
        dataAccess.addFurniture(furniture26);
        dataAccess.addFurniture(furniture27);
        dataAccess.addFurniture(furniture28);
        dataAccess.addFurniture(furniture29);
        dataAccess.addFurniture(furniture30);
        dataAccess.addFurniture(furniture31);
        dataAccess.addFurniture(furniture32);
        dataAccess.addFurniture(furniture33);
        dataAccess.addFurniture(furniture34);
        dataAccess.addFurniture(furniture35);
        dataAccess.addFurniture(furniture36);
        dataAccess.addFurniture(furniture37);
        dataAccess.addFurniture(furniture38);
        dataAccess.addFurniture(furniture39);
        dataAccess.addFurniture(furniture40);
        dataAccess.addFurniture(furniture41);
        dataAccess.addFurniture(furniture42);
        dataAccess.addFurniture(furniture43);
        dataAccess.addFurniture(furniture44);
        dataAccess.addFurniture(furniture45);
        dataAccess.addFurniture(furniture46);
        dataAccess.addFurniture(furniture47);
        dataAccess.addFurniture(furniture48);
        dataAccess.addFurniture(furniture49);
        dataAccess.addFurniture(furniture50);
        dataAccess.addFurniture(furniture51);
        dataAccess.addFurniture(furniture52);
        dataAccess.addFurniture(furniture53);
        dataAccess.addFurniture(furniture54);
        dataAccess.addFurniture(furniture55);
        dataAccess.addFurniture(furniture56);
        dataAccess.addFurniture(furniture57);
        dataAccess.addFurniture(furniture58);
        dataAccess.addFurniture(furniture59);
        dataAccess.addFurniture(furniture60);
        dataAccess.addFurniture(furniture61);
        dataAccess.addFurniture(furniture62);
        dataAccess.addFurniture(furniture63);
        dataAccess.addFurniture(furniture64);
        dataAccess.addFurniture(furniture65);
        dataAccess.addFurniture(furniture66);
        dataAccess.addFurniture(furniture67);
        dataAccess.addFurniture(furniture68);
        dataAccess.addFurniture(furniture69);
        dataAccess.addFurniture(furniture70);
        dataAccess.addFurniture(furniture71);
        dataAccess.addFurniture(furniture72);
        dataAccess.addFurniture(furniture73);
        dataAccess.addFurniture(furniture74);
        dataAccess.addFurniture(furniture75);
        dataAccess.addFurniture(furniture76);
        dataAccess.addFurniture(furniture77);
        dataAccess.addFurniture(furniture78);
        dataAccess.addFurniture(furniture79);
        dataAccess.addFurniture(furniture80);
        dataAccess.addFurniture(furniture81);
        dataAccess.addFurniture(furniture82);
        dataAccess.addFurniture(furniture83);
        dataAccess.addFurniture(furniture84);
        dataAccess.addFurniture(furniture85);
        dataAccess.addFurniture(furniture86);
        dataAccess.addFurniture(furniture87);
        dataAccess.addFurniture(furniture88);
        dataAccess.addFurniture(furniture89);
        dataAccess.addFurniture(furniture90);
        dataAccess.addFurniture(furniture91);
        dataAccess.addFurniture(furniture92);
        dataAccess.addFurniture(furniture93);
        dataAccess.addFurniture(furniture94);
        dataAccess.addFurniture(furniture95);
        dataAccess.addFurniture(furniture96);
        dataAccess.addFurniture(furniture97);
        dataAccess.addFurniture(furniture98);
        dataAccess.addFurniture(furniture99);
        dataAccess.addFurniture(furniture100);
        dataAccess.addFurniture(furniture101);
        dataAccess.addFurniture(furniture102);
        dataAccess.addFurniture(furniture103);
        dataAccess.addFurniture(furniture104);
        dataAccess.addFurniture(furniture105);
        dataAccess.addFurniture(furniture106);
        dataAccess.addFurniture(furniture107);
        dataAccess.addFurniture(furniture108);
        dataAccess.addFurniture(furniture109);
        dataAccess.addFurniture(furniture110);
        dataAccess.addFurniture(furniture111);
        dataAccess.addFurniture(furniture112);
        dataAccess.addFurniture(furniture113);
        dataAccess.addFurniture(furniture114);
        dataAccess.addFurniture(furniture115);
        dataAccess.addFurniture(furniture116);
        dataAccess.addFurniture(furniture117);
        dataAccess.addFurniture(furniture118);
        dataAccess.addFurniture(furniture119);
        dataAccess.addFurniture(furniture120);
        dataAccess.addFurniture(furniture121);
        dataAccess.addFurniture(furniture122);
        dataAccess.addFurniture(furniture123);
        dataAccess.addFurniture(furniture124);
        dataAccess.addFurniture(furniture125);
        dataAccess.addFurniture(furniture126);
        dataAccess.addFurniture(furniture127);
        dataAccess.addFurniture(furniture128);
        dataAccess.addFurniture(furniture129);
        dataAccess.addFurniture(furniture130);
        dataAccess.addFurniture(furniture131);
        dataAccess.addFurniture(furniture132);
        dataAccess.addFurniture(furniture133);
        dataAccess.addFurniture(furniture134);
        dataAccess.addFurniture(furniture135);
        dataAccess.addFurniture(furniture136);
        dataAccess.addFurniture(furniture137);
        dataAccess.addFurniture(furniture138);
        dataAccess.addFurniture(furniture139);
        dataAccess.addFurniture(furniture140);
        dataAccess.addFurniture(furniture141);
        dataAccess.addFurniture(furniture142);
        dataAccess.addFurniture(furniture143);
        dataAccess.addFurniture(furniture144);
        dataAccess.addFurniture(furniture145);
        dataAccess.addFurniture(furniture146);
        dataAccess.addFurniture(furniture147);
        dataAccess.addFurniture(furniture148);
        dataAccess.addFurniture(furniture149);
        dataAccess.addFurniture(furniture150);
        dataAccess.addFurniture(furniture151);
        dataAccess.addFurniture(furniture152);
        dataAccess.addFurniture(furniture153);
        dataAccess.addFurniture(furniture154);
        dataAccess.addFurniture(furniture155);
        dataAccess.addFurniture(furniture156);
        dataAccess.addFurniture(furniture157);
        dataAccess.addFurniture(furniture158);
        dataAccess.addFurniture(furniture159);
        dataAccess.addFurniture(furniture160);
        dataAccess.addFurniture(furniture161);
        dataAccess.addFurniture(furniture162);
        dataAccess.addFurniture(furniture163);
        dataAccess.addFurniture(furniture164);
        dataAccess.addFurniture(furniture165);
        dataAccess.addFurniture(furniture166);
        dataAccess.addFurniture(furniture167);
        dataAccess.addFurniture(furniture168);
        dataAccess.addFurniture(furniture169);
        dataAccess.addFurniture(furniture170);
        dataAccess.addFurniture(furniture171);
        dataAccess.addFurniture(furniture172);
        dataAccess.addFurniture(furniture173);
        dataAccess.addFurniture(furniture174);
        dataAccess.addFurniture(furniture175);
        dataAccess.addFurniture(furniture176);
        dataAccess.addFurniture(furniture177);
        dataAccess.addFurniture(furniture178);
        dataAccess.addFurniture(furniture179);
        dataAccess.addFurniture(furniture180);
        dataAccess.addFurniture(furniture181);
        dataAccess.addFurniture(furniture182);
        dataAccess.addFurniture(furniture183);
        dataAccess.addFurniture(furniture184);
        dataAccess.addFurniture(furniture185);
        dataAccess.addFurniture(furniture186);
        dataAccess.addFurniture(furniture187);
        dataAccess.addFurniture(furniture188);
        dataAccess.addFurniture(furniture189);
        dataAccess.addFurniture(furniture190);
        dataAccess.addFurniture(furniture191);
        dataAccess.addFurniture(furniture192);
        dataAccess.addFurniture(furniture193);
        dataAccess.addFurniture(furniture194);
        dataAccess.addFurniture(furniture195);
        dataAccess.addFurniture(furniture196);
        dataAccess.addFurniture(furniture197);
        dataAccess.addFurniture(furniture198);
        dataAccess.addFurniture(furniture199);
        dataAccess.addFurniture(furniture200);
        dataAccess.addFurniture(furniture201);
        dataAccess.addFurniture(furniture202);
        dataAccess.addFurniture(furniture203);
        dataAccess.addFurniture(furniture204);




    }

    public static void main(String[] args) throws SQLException {
        new MainJdbc();
    }
}
